services:
  hasiltka:
    build: .
    container_name: hasiltka
    hostname: hasiltka
    restart: unless-stopped
    ports:
      - "5013:3000"
    volumes:
      - ./tka_cache.db:/usr/src/app/tka_cache.db
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
